# Generated by Django 2.2.9 on 2021-01-31 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotedb', '0002_auto_20171104_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
